### PR TITLE
fix(shared/InputSelect): suppress mousedown event on select

### LINKED ISSUE #421: Dropdown options in a context menu cannot be selected anymore
__Describe the Bug__

After update to `table-js@6.0.1`, it occurred that the options in `InputSelect` can't be selected anymore if the component is placed in a context. I'm sure this is because the dropdown options are rendered outside of the context menu which causes the menu to close on global mousedown.

__Steps to Reproduce__

1. Open the dropdown
2. Try to select any option

__Expected Behavior__

It should work.

__Environment__

Please complete the following information:

 - Browser: Chrome 78
 - OS: MacOS
 - Library version: `develop` with updated `table-js`

### PR DESCRIPTION
**Pull request by barmac**
This prevents closing context menu when option is selected. 

Closes #421 

Contains https://github.com/bpmn-io/dmn-js/pull/422

### CODE REVIEW

File: packages/dmn-js-shared/src/components/InputSelect.js [hunk 1]
```diff
@@ -89,10 +89,15 @@ export default class InputSelect extends Component {
     const container = this.renderer.getContainer();
 
     container.appendChild(this._portalEl);
+
+    // suppress mousedown event propagation to handle click events inside the component
+    this._portalEl.addEventListener('mousedown', stopPropagation);
```
Comment (philippfromme) [inline packages/dmn-js-shared/src/components/InputSelect.js]: Why are we not handling this behavior in the context menu component which is the one closing itself on click?

Comment (barmac) [reply packages/dmn-js-shared/src/components/InputSelect.js]: The context menu listens to [mousedown events now](https://github.com/bpmn-io/table-js/blob/master/src/features/context-menu/components/ContextMenuComponent.js#L213). The click event fires always after mousedown, so the context menu is already closed when the click can be handled.
