### PR TITLE
fix: variable name changes when element name/label changes

### LINKED ISSUE #863: Update variable name after element is renamed in each editor
### What should we do?

Update variable name after element is renamed in each editor.
This can be done via [NameChangeBehavior](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-boxed-expression/src/features/modeling/behavior/NameChangeBehavior.js), given that it is adjusted to each of the editors.

* [x] When an element's name changes, the name of the attached variable should update accordingly.
* [ ] When a variable is created, it should be named as the element (at least empty string).

### Why should we do it?

Variable name has to be equal to the element name if variable is present. This is part of the specification.

### PR DESCRIPTION
**Pull request by abdul99ahad**
Closes #863

### Proposed Changes

- [x] When creating or updating the label in Decision box, the variable name automatically updates 
- [x] Setting the element name automatically sets variable name

### CODE REVIEW

**Comment by barmac** [comment]
I don't see any changes regarding the decision table. Is it already present in that editor? I know that we don't support variable adding or modification in the decision table, but it could be present in the XML brought by user.

**Comment by abdul99ahad** [comment]
> I don't see any changes regarding the decision table. Is it already present in that editor? I know that we don't support variable adding or modification in the decision table, but it could be present in the XML brought by user.

Since variables weren't available in the modeling interface, I initially assumed they weren't part of the decision tables. However, I've now fixed the issue for all elements to ensure everything is covered.

File: packages/dmn-js-shared/src/features/modeling/behavior/NameChangeBehavior.js [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+  updateVariableFromLabel = ({ context }) => {
+    const { element, newLabel } = context;
+    const bo = getBusinessObject(element);
+
+    if (!bo.variable) {
+      return;
+    }
+
+    bo.variable.name = newLabel;
+    this._modeling.updateProperties(element, { variable: bo.variable });
```
Comment (barmac) [inline packages/dmn-js-shared/src/features/modeling/behavior/NameChangeBehavior.js:31]: This is a technique called monkey-patching. If you add tests for `commandStack.undo`, you will notice that the change cannot be undone. We need to dispatch an updateProperties call which updates the variable name.
@philippfromme perhaps it makes sense you look into this together with @abdul99ahad

**Review by barmac — CHANGES_REQUESTED** [review]
Notice the comment I left. Let's add tests for undo, and fix the code. As I am off for the next two weeks, please ask @philippfromme or other team member for support.

File: packages/dmn-js-shared/src/features/modeling/behavior/NameChangeBehavior.js (hunk 1 above)
Comment (abdul99ahad) [reply packages/dmn-js-shared/src/features/modeling/behavior/NameChangeBehavior.js]: Thanks, @barmac, for pointing this out. I discussed the monkey patching technique with @philippfromme earlier and I didn't realize that my implementation went against the recommended approach. I apologize for the oversight. I've updated the implementation to align with the correct approach.

**Comment by abdul99ahad** [comment]
> Notice the comment I left. Let's add tests for undo, and fix the code. As I am off for the next two weeks, please ask @philippfromme or other team member for support.

I have fixed the code and added the test cases that support undo/redo

**Comment by abdul99ahad** [comment]
@barmac @philippfromme We could move the `NameChangeBehavior` from dmn-boxed-expression to a shared `NameChangeBehavior`. The key difference is that the shared version only syncs the element name with the variable name, not the other way around, while the boxed-expression version supports both directions. Should we keep this distinction, or do we need to refactor?

**Comment by philippfromme** [comment]
> @barmac @philippfromme We could move the `NameChangeBehavior` from dmn-boxed-expression to a shared `NameChangeBehavior`. The key difference is that the shared version only syncs the element name with the variable name, not the other way around, while the boxed-expression version supports both directions. Should we keep this distinction, or do we need to refactor?

Is there anything keeping us from handling both ways?

**Comment by abdul99ahad** [comment]
> > @barmac @philippfromme We could move the `NameChangeBehavior` from dmn-boxed-expression to a shared `NameChangeBehavior`. The key difference is that the shared version only syncs the element name with the variable name, not the other way around, while the boxed-expression version supports both directions. Should we keep this distinction, or do we need to refactor?
> 
> Is there anything keeping us from handling both cases in a shared component?

We can cover that case as well. I previously discussed this with @barmac, who mentioned that only a one-way sync is required as of now.

File: packages/dmn-js-decision-table/test/spec/features/modeling/behavior/NameChangeBehaviorSpec.js [hunk 2]
```diff
@@ -0,0 +1,86 @@
+import { bootstrapModeler, inject } from 'test/helper';
+
+import decisionTableXML from './name-change-behavior.dmn';
+
+import CoreModule from 'src/core';
+import Modeling from 'src/features/modeling';
+
+
+describe('NameChangeBehavior', function() {
```
Comment (nikku) [inline packages/dmn-js-decision-table/test/spec/features/modeling/behavior/NameChangeBehaviorSpec.js:9]:
```suggestion
describe('features/modeling/behavior - NameChangeBehavior', function() {
```

**Comment by barmac** [comment]
I will look into this today again.

**Comment by barmac** [comment]
Note that the variable name change is not reflected in the literal expression editor:

https://github.com/user-attachments/assets/52f9448e-2267-409b-b609-9740f2b20bff

**Comment by barmac** [comment]
Looks that it's an already existing issue. https://github.com/bpmn-io/dmn-js/blob/c3e093984603e14e91daecb5cc11c9f34b3e7ff9/packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js does not update on external changes.

**Comment by barmac** [comment]
> > > @barmac @philippfromme We could move the `NameChangeBehavior` from dmn-boxed-expression to a shared `NameChangeBehavior`. The key difference is that the shared version only syncs the element name with the variable name, not the other way around, while the boxed-expression version supports both directions. Should we keep this distinction, or do we need to refactor?
> > 
> > 
> > Is there anything keeping us from handling both cases in a shared component?
> 
> We can cover that case as well. I previously discussed this with @barmac, who mentioned that only a one-way sync is required as of now.

The thing about this is that in the future, I expect that we replace dmn-js-literal-expression with dmn-js-boxed-expression entirely where you cannot change the variable name by design. Still, I think that for the external changes it makes sense to sync it two-way.

**Comment by abdul99ahad** [comment]
> Note that the variable name change is not reflected in the literal expression editor:
> 
>  Screen.Recording.2024-09-13.at.10.40.49.mov

Yes, the variable name is changing but the state is not updating. Hence, when you're on the same screen (lieral expression editor), the change doesn't reflect although its value has been updated. 

For variable name changing directly, the element name won't change since it's currently not supported.

**Comment by barmac** [comment]
> Yes, the variable name is changing but the state is not updating. Hence, when you're on the same screen (lieral expression editor), the change doesn't reflect although its value has been updated.

IMO the update should happen as it does in boxed expression. Let the field display the current value.

**Comment by abdul99ahad** [comment]
> > Yes, the variable name is changing but the state is not updating. Hence, when you're on the same screen (lieral expression editor), the change doesn't reflect although its value has been updated.
> 
> IMO the update should happen as it does in boxed expression. Let the field display the current value.

@barmac need your support in updating the state externally as I'm stuck and can only update the state within the component. We might need to use Wrapper with ChangeSupport just like in boxed-expression.

File: packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js [hunk 3]
```diff
@@ -32,6 +32,21 @@ export default class LiteralExpressionPropertiesComponent extends Component {
     });
   }
 
+  componentWillMount() {
+    this._eventBus.on('elements.changed', this.onChange);
+    console.log('componentDidUpdate',);
```
Comment (barmac) [inline packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js:37]:
```suggestion
```

File: packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js [hunk 4]
```diff
@@ -32,6 +32,21 @@ export default class LiteralExpressionPropertiesComponent extends Component {
...
+  }
+
+  componentWillUnmount() {
+    this._eventBus.off('elements.changed', this.onChange);
+  }
+
+  onChange = () => {
+    this.setState({
+      name: this._viewer.getDecision().variable.name
```
Comment (barmac) [inline packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js:46]: How will this work in case no variable is added to a decision? I am speaking of cases like:

```xml
  <decision id="Decision_1kfrmu8" name="Decision 1">
    <literalExpression id="LiteralExpression_0lr3hs5">
      <text>a</text>
    </literalExpression>
  </decision>
```

While it cannot be created in our tool, it's a valid DMN which would have failed due to missing variable.

Comment (abdul99ahad) [reply packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js:46]: In this case, should the text be treated as a variable, or should we ignore the variable and avoid updating the state?

Comment (barmac) [reply packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js:46]: Ideally, I'd expect a variable to be created when we change the name or type. I see that it's probably scope creep since we don't handle cases like [above](https://github.com/bpmn-io/dmn-js/pull/893#discussion_r1771043404). So for now, I'd only expect that we don't add another place where the component may crash. Code-wise, this means that I'd not update the state if a variable is missing completely.

**Comment by barmac** [comment]
The CI failure seems to be unrelated. I'll give it a second try.

File: packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js [hunk 5]
```diff
@@ -32,6 +32,23 @@ export default class LiteralExpressionPropertiesComponent extends Component {
...
+    this._eventBus.on('elements.changed', this.onChange);
+  }
+
+  componentWillUnmount() {
+    this._eventBus.off('elements.changed', this.onChange);
+  }
+
+  onChange = () => {
+    const decision = this._viewer.getDecision();
+    if (decision.variable) {
```
Comment (barmac) [inline packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js:45]: 🚀

**Review by barmac — APPROVED** [review]

File: packages/dmn-js-drd/src/features/modeling/cmd/UpdatePropertiesHandler.js [hunk 6]
```diff
@@ -37,8 +39,8 @@ UpdatePropertiesHandler.$inject = [ 'elementRegistry', 'moddle' ];
  */
 UpdatePropertiesHandler.prototype.execute = function(context) {
 
-  var element = context.element,
-      changed = [ element ];
+  const { element, properties } = context,
```
Comment (barmac) [inline packages/dmn-js-drd/src/features/modeling/cmd/UpdatePropertiesHandler.js:42]: [optional] I'd consider to either have all declarations in ES6 (const, let), or leave this file with `var`s only. Right now it looks weird.

**Comment by barmac** [comment]
One optional improvement suggestion, but other than that it looks good.

File: packages/dmn-js-shared/src/features/modeling/behavior/NameChangeBehavior.js [hunk 7]
```diff
@@ -0,0 +1,87 @@
...
+  isVariable(element) {
+    const parent = getParent(element);
+    return (
+      is(element, 'dmn:InformationItem') &&
+      parent && parent.get('variable') === element
+    );
+  }
+
+  isElementVariable(element) {
+    const variable = element.get('variable');
```
Comment (nikku) [inline packages/dmn-js-shared/src/features/modeling/behavior/NameChangeBehavior.js:72]: This breaks when using this feature along with the [dmn-js-properties-panel](https://github.com/bpmn-io/dmn-js-properties-panel).

Comment (nikku) [reply packages/dmn-js-shared/src/features/modeling/behavior/NameChangeBehavior.js:72]: Cf. https://github.com/bpmn-io/dmn-js-properties-panel/issues/103

Comment (barmac) [reply packages/dmn-js-shared/src/features/modeling/behavior/NameChangeBehavior.js:72]: Ouch. I can reproduce it on the Modeler nightly too.
