### PR TITLE
Fix issues found with axe

### LINKED ISSUE #821: DMN elements - Scrollable region must have keyboard access
### Describe the Bug

The hit policy selector and the DMN table are affected by accessibility issue: **Scrollable region must have keyboard access**.

AXE recommendation:
To solve this problem, you need to fix at least (1) of the following:
* Element should have focusable content
* Element should be focusable

image

### Steps to Reproduce

1. Open the DMN editor (for example on the Web Modeler)
2. Open the hit policy selector
3. Resize the page so that the internal scrollbar appears on both elements (see screenshot)
4. Execute the page scan, by using the ["axe DevTools" extension](https://www.deque.com/axe/devtools/)

### Expected Behavior

No accessibility issue is reported by the axe scan.

### Environment

Please complete the following information:

 - Browser: Chrome
 - OS: macOs
 - Library version: current one (reproducible on https://demo.bpmn.io/dmn/new)

### PR DESCRIPTION
**Pull request by barmac**
Related to https://github.com/camunda/product-hub/issues/2189

Closes #821

### CODE REVIEW

**Comment by barmac** [comment]
I will push more changes to this PR so that we can merge it more easily. Otherwise I'd have to open PRs based on this branch.

File: packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js [hunk 1]
```diff
@@ -167,8 +163,12 @@ class TableCellEditor extends Component {
...
   }
 
-  getDefaultExpressionLanguage(businessObject) {
-    const elementType = is(businessObject, 'dmn:UnaryTests') ? 'inputCell' : 'outputCell';
+  _isInputCell() {
+    return is(this.props.businessObject, 'dmn:UnaryTests');
+  }
+
+  getDefaultExpressionLanguage() {
+    const elementType = this._isInputCell() ? 'inputCell' : 'outputCell';
```
Comment (marstamm) [inline packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js:171]: As I understand this, This is just a refactoring to get the businessObject from the props instead of having it passed to the function, correct?

If so, we can then also adjust the function call in `isScript` for consistency. (non-blocking, can be done as follow-up)

https://github.com/bpmn-io/dmn-js/blob/49a586d6a6e5abf548b65afc14bde2163ab998ae/packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js#L152

File: packages/dmn-js-drd/src/features/drill-down/DrillDown.js [hunk 2]
```diff
@@ -93,6 +91,28 @@ export default class DrillDown {
...
+
+    const button = document.createElement('button');
+    button.type = 'button';
+    button.className = className;
+    button.title = this._translate(title);
+
+    container.appendChild(button);
+
+    return container;
+  }
```
Comment (marstamm) [inline packages/dmn-js-drd/src/features/drill-down/DrillDown.js:114]: What is the reason we are not using `domify` here? Personally, I find it easier to read than building with native API.

The function name can be confusing, as we return a DOM node and not HTML. We could consider renaming it to `_getOverlayNode`, but we do use it interchangeably in other places

File: packages/dmn-js-drd/test/spec/features/drill-down/DrillDownSpec.js [hunk 3]
```diff
@@ -88,6 +88,37 @@ describe('features - drilldown', function() {
 
       });
 
+
+      describe('accessibility', function() {
+
+
+        verify(
```
Comment (marstamm) [inline packages/dmn-js-drd/test/spec/features/drill-down/DrillDownSpec.js:95]: Code Style
```suggestion
      describe('accessibility', function() {

        verify(
```

File: packages/dmn-js-shared/test/spec/components/EditableComponentSpec.js [hunk 4]
```diff
@@ -91,6 +91,19 @@ describe('components/EditableComponent', function() {
...
+      <TestComponent value={ null } label="label" />
+    );
+
+    // then
+    expect(node.innerHTML).to.match(/aria-label="label"/);
+  });
+
+
+
   describe('empty class', function() {
```
Comment (marstamm) [inline packages/dmn-js-shared/test/spec/components/EditableComponentSpec.js:107]: Code Style
```suggestion
  });


  describe('empty class', function() {
```

File: packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js (hunk 1 above)
Comment (barmac) [reply packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js:171]: OK

File: packages/dmn-js-drd/src/features/drill-down/DrillDown.js (hunk 2 above)
Comment (barmac) [reply packages/dmn-js-drd/src/features/drill-down/DrillDown.js:114]: I wanted to reduce the risks of having accidental XSS vector. Note that `domify` doesn't care whether the result of `translate` call contains quotation marks which otherwise would have to be escaped.

Comment (barmac) [reply packages/dmn-js-drd/src/features/drill-down/DrillDown.js]: I renamed the method.

File: packages/dmn-js-shared/test/spec/components/EditableComponentSpec.js (hunk 4 above)
Comment (barmac) [reply packages/dmn-js-shared/test/spec/components/EditableComponentSpec.js]: If only there was a linting rule for this 🤡

**Comment by marstamm** [comment]
I found 1 more issue with the axe dev tool. The Expression language dropdown does not have a label. I am not sure if this is relevant at all, as we do not have this field in C8.
image

Otherwise, looks very clean! Great work 👏

File: packages/dmn-js-drd/src/features/drill-down/DrillDown.js (hunk 2 above)
Comment (marstamm) [reply packages/dmn-js-drd/src/features/drill-down/DrillDown.js]: Makes sense, let's keep it like this then 👍

**Review by marstamm — APPROVED** [review]
🚀

**Comment by barmac** [comment]
> fix: ensure accessible names for expression language select

Done via https://github.com/bpmn-io/dmn-js/pull/843/commits/af13b8dcef9642bcdd00c38ee800a762363e184b

File: packages/dmn-js-shared/test/spec/components/EditableComponentSpec.js (hunk 4 above)
Comment (nikku) [reply packages/dmn-js-shared/test/spec/components/EditableComponentSpec.js]: It is [you to create one](https://github.com/bpmn-io/eslint-plugin-bpmn-io) :wink:.
